name: testproject
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  persian_number_utility: ^1.1.4
  injectable: ^2.5.0
  logger: ^2.5.0
  get_it: ^8.0.3
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.7
  rxdart: ^0.28.0
  pretty_dio_logger: ^1.4.0
  curl_logger_dio_interceptor: ^1.0.0
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.3
  retrofit: ^4.4.2
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  flutter_bounceable: ^1.1.0
  go_router: ^15.1.1
  hive: ^2.2.3
  path_provider: ^2.1.5
  crypto: ^3.0.6
  easy_dynamic_theme: ^2.3.1
  shared_preferences: ^2.5.3
  persian_datetime_picker: ^3.1.0
  multiple_stream_builder: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  injectable_generator: ^2.7.0
  retrofit_generator: ^9.1.9
  json_serializable: ^6.9.4
  

  flutter_lints: ^5.0.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true

  # colors:
  #   inputs:
  #     - assets/color/colors.xml

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
